# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [4]:
import numpy as np
import pandas as pd

#### 2. Print the numpy version and the configuration (★☆☆)

In [17]:
print(np.__version__)

2.1.3


#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
null = np.zeros(10)
print(null)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [16]:
print(null.nbytes)
print(null.itemsize)

80
8


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [24]:
null_2 = np.zeros(10)
null_2[9] = 1
print(null_2)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [25]:
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [27]:
reversed_vector = np.flip(vector)
print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [28]:
matrix = np.arange(0,9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [36]:
identity_matrix = np.identity(3)
print(identity_matrix)
#or 
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [41]:
random_square_matrix = np.random.randint(1, 10, (3, 3))
print(random_square_matrix)
# note: everytime you run this cell, it will generate a new random square matrix

[2 1]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [48]:
rand_matrix = np.random.randint(size = (10,10), low = 0, high = 100)
print(rand_matrix)
print(rand_matrix.min())
print(rand_matrix.max())


[[86 82 92 39 43 93 88  1 81 16]
 [42 85 81 11 79 46 71 34 39 27]
 [38 46 63 38 90 85 12 84 84 71]
 [99  8 98 78 96 88 57 77 72 28]
 [34 39 40 81  8  3  0 38 77 74]
 [37 71 25 59 13 75 23 91 27 73]
 [91 90 29 58 34 48 89  5 68 71]
 [70 91 50 76 84 64 36 81 90 78]
 [94  8 43 30 51 70 42 89 10  2]
 [32 83 20 91 29 79 37 62 73 48]]
0
99


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [62]:
rand_vector = np.random.randint(size = (30), low = 0, high = 100)
print(rand_vector)
print(rand_vector.mean())
print(np.median(rand_vector))
print(rand_vector.var())
print(rand_vector.std())



[46 16 77 81 11 40 18 41 74 12 33 63 29  0  7  0 85 37  4 49 45 51 54 74
  4 36  7 97 88 64]
41.43333333333333
40.5
843.112222222222
29.036394786925978


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [71]:
box = np.empty((10,10))
for i in range(10):
    for j in range(10):
        if i == 0  or i == 9 or j == 0 or j == 9:
            box[i][j] = 1
        else:
            box[i][j] = 0
print(box)

# O R -------------
arr = np.ones((5, 5), dtype=int)   # start with all 1s
arr[1:-1, 1:-1] = 0                # set inner elements to 0

print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [82]:
bordered = np.pad(box, pad_width=1, mode='constant', constant_values=0)
print(bordered)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [78]:
print(np.nan)
print(np.inf)
print(np.nan - np.nan)
print(np.inf > np.inf)
print(np.nan in set([np.nan]))
print(0 * np.inf)
print(0.3 == 3 * 0.1)

nan
inf
nan
False
True
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [80]:
arr = np.diag([1, 2, 3, 4], k=-1)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [83]:
checkerboard = np.zeros((8,8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)
#this syntax is new for me.             start:end:step

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
# if we fill x first then y, then z
# the first 2D matrix is filled with 6 x 7 elements = 42 
# so for the 100th element, 42 + 42 = 84 so look in 3rd matrix
# we fill rows first then columns, left elements = 16. therefore 6 + 6 = 12
# third row, 4th column, 3rd 2D matrix, therefore answer = (3,4,2)
# okay this is entirely wrong- first mistake = numpy arrays are 0-indexed
# next mistake = 3D arrays are like books in numpy, first z is filled, followed by y, then x
#therefore -> 7*8 = 56 in first page, then 44 left -> 7 * 6 = 42 in second page, 2 left, 
# considering 0-based Indexing, (1,)






#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [87]:
pattern = [[0, 1], [1, 0]]
checkerboard = np.tile(pattern, (4, 4))
print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [88]:
matrix = np.random.randint(1, 10, (5, 5))
print(matrix)
min = np.min(matrix)
max = np.max(matrix)
matrix_normalised = (matrix - min) / (max - min)
print(matrix_normalised)
# i couldn't find a function to normalise the matrix, so i used the formula

[[6 6 6 7 5]
 [6 6 8 7 4]
 [3 4 2 6 2]
 [7 5 8 7 9]
 [9 1 1 7 2]]
[[0.625 0.625 0.625 0.75  0.5  ]
 [0.625 0.625 0.875 0.75  0.375]
 [0.25  0.375 0.125 0.625 0.125]
 [0.75  0.5   0.875 0.75  1.   ]
 [1.    0.    0.    0.75  0.125]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [91]:
rgba = np.dtype([
    ('r', 'u1'),
    ('g', 'u1'),
    ('b', 'u1'),
    ('a', 'u1')
])
pixels = np.array([
    (255, 0, 0, 255),   # Red
    (0, 255, 0, 128),   # Green (half transparent)
    (0, 0, 255, 64)     # Blue (faint)
], dtype=rgba)

print(pixels['r'])
print(pixels['g'])
print(pixels['b'])
print(pixels['a'])



[255   0   0]
[  0 255   0]
[  0   0 255]
[255 128  64]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [96]:
matrix1 = np.random.randint(1,10, (5,3))
matrix2 = np.random.randint(1,10, (3,2))


print(matrix1)
print(matrix2)
print("-----------------------------------")
# there are multiple ways to multiply two matrices
print(matrix1 @ matrix2)
print(matrix1.dot(matrix2))
print(np.dot(matrix1, matrix2))
print(np.matmul(matrix1, matrix2))

[[5 4 5]
 [4 6 6]
 [6 7 3]
 [8 8 3]
 [8 1 2]]
[[2 4]
 [2 3]
 [1 8]]
-----------------------------------
[[23 72]
 [26 82]
 [29 69]
 [35 80]
 [20 51]]
[[23 72]
 [26 82]
 [29 69]
 [35 80]
 [20 51]]
[[23 72]
 [26 82]
 [29 69]
 [35 80]
 [20 51]]
[[23 72]
 [26 82]
 [29 69]
 [35 80]
 [20 51]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [100]:
array = np.random.randint(1, 10, (10))
for i in range(10):
    if array[i] > 3 and array[i] < 8:
        array[i] = array[i] * (-1)
print(array)

[ 2  1  1  2 -5 -7  2 -5 -7  1]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [103]:
print(sum(range(5),-1))
# the second argument of sum is the start value
from numpy import *
print(sum(range(5),-1))
# the second argument of sum is the axis of numpy.sum library

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [121]:
Z = np.random.randint(0,5, size=(10))
print(Z)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
# print(Z<Z>Z)


[0 3 1 0 2 0 0 2 2 0]
[ 1 27  1  1  4  1  1  4  4  1]
[0 4 1 0 2 0 0 2 2 0]
[False False False False False False False False False False]
[0.+0.j 0.+3.j 0.+1.j 0.+0.j 0.+2.j 0.+0.j 0.+0.j 0.+2.j 0.+2.j 0.+0.j]
[0. 3. 1. 0. 2. 0. 0. 2. 2. 0.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [123]:
print(np.array(0) / np.array(0)) # -- nan 0 / 0 undefined
print(np.array(0) // np.array(0)) # -- floor division - > 0 
print(np.array([np.nan]).astype(int).astype(float)) # 0.
# all these give RuntimeWarning.
##### ----------- ###### this is bruhh

nan
0
[0.]


/var/folders/hd/f4hrkdg95y97wjwq1_hpdx5r0000gn/T/ipykernel_26040/3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/var/folders/hd/f4hrkdg95y97wjwq1_hpdx5r0000gn/T/ipykernel_26040/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/var/folders/hd/f4hrkdg95y97wjwq1_hpdx5r0000gn/T/ipykernel_26040/3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [127]:
Z = np.array([1.2, 1.5, -1.2, -1.5])
print(np.copysign(np.ceil(np.abs(Z)), Z))

[ 2.  2. -2. -2.]


#### 30. How to find common values between two arrays? (★☆☆)

In [130]:
Y = np.array([1,2,3,4,5])    
Z = np.array([1,2,3,4,5,6,7,8,9,10])
print(np.array(list(set(Y) & set(Z))))
#this gives intersection of two arrays

[1 2 3 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
np.seterr(all='ignore')

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [131]:
np.sqrt(-1) == np.emath.sqrt(-1)

/var/folders/hd/f4hrkdg95y97wjwq1_hpdx5r0000gn/T/ipykernel_26040/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [134]:
from datetime import date, timedelta

today = date.today()
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2025-11-24
Today: 2025-11-25
Tomorrow: 2025-11-26


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [137]:
dates = np.arange('2025-07', '2025-08', dtype='datetime64[D]')
print(dates)

['2025-07-01' '2025-07-02' '2025-07-03' '2025-07-04' '2025-07-05'
 '2025-07-06' '2025-07-07' '2025-07-08' '2025-07-09' '2025-07-10'
 '2025-07-11' '2025-07-12' '2025-07-13' '2025-07-14' '2025-07-15'
 '2025-07-16' '2025-07-17' '2025-07-18' '2025-07-19' '2025-07-20'
 '2025-07-21' '2025-07-22' '2025-07-23' '2025-07-24' '2025-07-25'
 '2025-07-26' '2025-07-27' '2025-07-28' '2025-07-29' '2025-07-30'
 '2025-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [143]:
A = 4
B = 3

B += A
A *= -0.5
B *= A

print(B)


-14.0


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [155]:
array = np.random.uniform(1,10, size=(10))
print(array)

# now for the integer part
print(np.fix(array))
print(np.floor(array))
print(array.astype(int))
print(np.trunc(array))



[8.42093459 7.68756341 4.9763476  1.54972331 1.18317645 4.02950648
 5.29974699 3.64303669 8.85435869 6.07440517]
[8. 7. 4. 1. 1. 4. 5. 3. 8. 6.]
[8. 7. 4. 1. 1. 4. 5. 3. 8. 6.]
[8 7 4 1 1 4 5 3 8 6]
[8. 7. 4. 1. 1. 4. 5. 3. 8. 6.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
Z = np.tile(np.arange(5), (5,1))
print(Z)

[[0 1 2 3 4 0 1 2 3 4]
 [0 1 2 3 4 0 1 2 3 4]
 [0 1 2 3 4 0 1 2 3 4]
 [0 1 2 3 4 0 1 2 3 4]
 [0 1 2 3 4 0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generate():
    for x in range(10):
        yield x
# yield is used to return a value from a function
Z = np.fromiter(generate(), dtype=float, count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [162]:
Z = np.random.rand(10)
print(Z)


[0.81728253 0.06985071 0.54768879 0.2432608  0.34648886 0.34866747
 0.05000686 0.56860134 0.15412736 0.16968499]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [166]:
Z = np.random.randint(1,100, size=(10))
print("Original array:", Z)
Z.sort()
print("Sorted array:", Z)

Original array: [89  1 52 54 36 19 41 60 56 55]
Sorted array: [ 1 19 36 41 52 54 55 56 60 89]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [169]:
Z = np.arange(10)
print(Z)
# np.add.reduce is faster for small arrays
print(np.add.reduce(Z))

[0 1 2 3 4 5 6 7 8 9]
45


#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [172]:
A = np.array([1,2,3])
B = np.array([1,2,3])
print(np.array_equal(A,B))

True


#### 43. Make an array immutable (read-only) (★★☆)

In [174]:
Z = np.zeros(10)
Z.flags.writeable = False
# we can check using try and catch block

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [178]:
Z = np.random.randint(1,100,size=(10))
print(Z)
Z[Z.argmax()] = 0
print(Z)


[ 4 28 88 71 67 79 55  6  5 90]
[ 4 28 88 71 67 79 55  6  5  0]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)